#!/usr/bin/env python3
"""
IntentGuard Entrypoint
CLI and GitHub Actions entry point for the agentic PR reviewer.
"""

import os
import sys
import argparse
import json
import traceback
from datetime import datetime

from dotenv import load_dotenv

from agent.graph import run_review
from agent.tools import GitHubTool


load_dotenv()


# ============================================================================
# Report Formatter
# ============================================================================

def format_report(state: dict) -> str:
    """Format final state into a GitHub PR comment."""
        summary = state.get("summary")
            if not summary:
                    return "❌ Review failed to generate summary."
                        
                            findings = state.get("findings", [])
                                
                                    # Header
                                        lines = [
                                                "# 🔍 IntentGuard Agentic Review Report",
                                                        "",
                                                                f"**Verdict:** `{summary.overall_verdict.upper()}`",
                                                                        f"**Estimated Effort:** {summary.estimated_effort}",
                                                                                f"**Total Findings:** {summary.total_findings}",
                                                                                        "",
                                                                                                "## Severity Breakdown",
                                                                                                        f"- 🚨 Critical: {summary.critical_count}",
                                                                                                                f"- ⚠️ High: {summary.high_count}",
                                                                                                                        f"- ℹ️ Medium: {summary.medium_count}",
                                                                                                                                f"- 💡 Low: {summary.low_count}",
                                                                                                                                        "",
                                                                                                                                                "---",
                                                                                                                                                        "",
                                                                                                                                                            ]
                                                                                                                                                                
                                                                                                                                                                    # Summary text
                                                                                                                                                                        lines.append(summary.summary_text)
                                                                                                                                                                            lines.append("")
                                                                                                                                                                                
                                                                                                                                                                                    # Recommendations
                                                                                                                                                                                        if summary.recommendations:
                                                                                                                                                                                                lines.append("## 📋 Recommendations")
                                                                                                                                                                                                        for rec in summary.recommendations:
                                                                                                                                                                                                                    lines.append(f"- {rec}")
                                                                                                                                                                                                                            lines.append("")
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                    # Detailed findings table
                                                                                                                                                                                                                                        if findings:
                                                                                                                                                                                                                                                lines.append("## Detailed Findings")
                                                                                                                                                                                                                                                        lines.append("")
                                                                                                                                                                                                                                                                lines.append("| Agent | Severity | File | Line | Title |")
                                                                                                                                                                                                                                                                        lines.append("|-------|----------|------|------|-------|")
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                        for f in findings:
                                                                                                                                                                                                                                                                                                    file_link = f"`{f.file_path}:{f.line_start}`"
                                                                                                                                                                                                                                                                                                                lines.append(f"| {f.agent} | {f.severity.upper()} | {file_link} | {f.line_start} | {f.title[:50]}... |")
                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                lines.append("")
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                        # Raw agent outputs (collapsible)
                                                                                                                                                                                                                                                                                                                                            lines.append("<details>")
                                                                                                                                                                                                                                                                                                                                                lines.append("<summary>🤖 Raw Agent Outputs (click to expand)</summary>")
                                                                                                                                                                                                                                                                                                                                                    lines.append("")
                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                            for agent in ["security", "quality", "qa", "alignment"]:
                                                                                                                                                                                                                                                                                                                                                                    raw = state.get(f"{agent}_raw", "")
                                                                                                                                                                                                                                                                                                                                                                            if raw:
                                                                                                                                                                                                                                                                                                                                                                                        lines.append(f"### {agent.capitalize()} Agent")
                                                                                                                                                                                                                                                                                                                                                                                                    lines.append("```")
                                                                                                                                                                                                                                                                                                                                                                                                                lines.append(raw[:2000])  # Truncate for comment size
                                                                                                                                                                                                                                                                                                                                                                                                                            lines.append("```")
                                                                                                                                                                                                                                                                                                                                                                                                                                        lines.append("")
                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                lines.append("</details>")
                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Footer
                                                                                                                                                                                                                                                                                                                                                                                                                                                            lines.append("")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                lines.append("---")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lines.append(f"*Generated by IntentGuard at {datetime.utcnow().isoformat()}Z*")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return "\n".join(lines)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ============================================================================
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Main Execution
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # ============================================================================

                                                                                                                                                                                                                                                                                                                                                                                                                                                                            def main():
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser = argparse.ArgumentParser(description="IntentGuard - Agentic PR Reviewer")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument("--pr", type=int, required=True, help="PR number")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        parser.add_argument("--repo", type=str, default=os.getenv("GITHUB_REPOSITORY"), help="Repo name (owner/repo)")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            parser.add_argument("--dry-run", action="store_true", help="Run without posting to GitHub")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                parser.add_argument("--output", type=str, help="Save report to file path")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    parser.add_argument("--ticket", type=str, help="Explicit ticket ID for alignment")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            args = parser.parse_args()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if not args.repo:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("Error: --repo required or set GITHUB_REPOSITORY env var", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Fetch PR data
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print(f"🔍 Fetching PR #{args.pr} from {args.repo}...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            gh = GitHubTool()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    pr = gh.fetch_pr(args.repo, args.pr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"✅ PR fetched: {pr.title}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        print(f"❌ Failed to fetch PR: {e}", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        # Run review
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🚀 Starting IntentGuard review...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("   └─ Running 4 agents in parallel: Security | Quality | QA | Alignment")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                final_state = run_review(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pr_url=pr.html_url if hasattr(pr, 'html_url') else f"https://github.com/{args.repo}/pull/{args.pr}",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pr_number=pr.number,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    repo_name=args.repo,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pr_diff=pr.diff,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pr_title=pr.title,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        pr_description=pr.description,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    branch_name=pr.branch,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                author=pr.author,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ticket_id=args.ticket,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        files_changed=pr.files_changed,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    lines_added=pr.additions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                lines_deleted=pr.deletions,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        )
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("✅ Review complete!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"❌ Review failed: {e}", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    traceback.print_exc()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Format and output
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        report = format_report(final_state)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if args.output:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        with open(args.output, "w", encoding="utf-8") as f:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    f.write(report)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(f"📝 Report saved to {args.output}")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    # Post to GitHub unless dry-run
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if not args.dry_run:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("💬 Posting review comment to GitHub...")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        try:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    gh.post_comment(args.repo, args.pr, report)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("✅ Comment posted successfully!")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        except Exception as e:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print(f"⚠️ Failed to post comment: {e}", file=sys.stderr)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                # Don't fail the action if comment posting fails
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("🧪 Dry run mode - skipping GitHub comment")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n" + "="*60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print(report)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("="*60)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Exit with appropriate code
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                verdict = final_state.get("summary", {}).overall_verdict if final_state.get("summary") else "failed"
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if verdict == "rejected":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            print("\n❌ PR rejected due to critical issues")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    sys.exit(1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        elif verdict == "needs_changes":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                print("\n⚠️ PR needs changes before approval")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        sys.exit(0)  # Don't fail CI, just inform
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            else:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    print("\n✅ PR approved")
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            sys.exit(0)


                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if __name__ == "__main__":
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                main()
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 